// Centralized icon exports for AgendaIQ - Tree-shaking optimized

// Feather Icons - Most commonly used
export { 
  User as FiUser, 
  Mail as FiMail, 
  Lock as FiLock, 
  AlertCircle as FiAlertCircle,
  Download as FiDownload,
  Eye as FiEye,
  Edit as FiEdit,
  Trash2 as FiTrash2,
  RefreshCw as FiRefreshCw,
  Database as FiDatabase,
  Activity as FiActivity,
  Shield as FiShield,
  AlertTriangle as FiAlertTriangle,
  Plus as FiPlus,
  Clock as FiClock,
  FileText as FiFileText,
  Users as FiUsers,
  Check as FiCheck,
  X as FiX,
  Upload as FiUpload,
  Save as FiSave,
  FiArrowLeft,
  ChevronDown,
  ChevronRight,
  UserCheck as FiUserCheck,
  Home as FiHome,
  TrendingUp as FiTrendingUp,
  Settings as FiSettings,
  FiSearch,
  FiFilter,
  Calendar as FiCalendar,
  FiMoreVertical,
  FiBell,
  FiMenu,
  FiLogOut,
  FiInfo,
  FiHelpCircle,
  FiExternalLink,
  FiCopy,
  FiFolder,
  FiFile,
  FiImage,
  FiVideo,
  FiMusic,
  FiMic,
  FiCamera,
  FiMap,
  FiGlobe,
  FiWifi,
  FiPhone,
  FiMessageCircle,
  FiSend,
  FiPaperclip,
  Book as FiBookmark,
  FiHeart,
  FiStar,
  FiThumbsUp,
  FiShare2,
  FiFlag,
  FiTag,
  FiGrid,
  FiList,
  FiMaximize2,
  FiMinimize2,
  FiPlay,
  FiPause,
  FiSkipBack,
  FiSkipForward,
  FiVolume2,
  FiVolumeX,
  FiShuffle,
  FiRepeat,
  FiZoomIn,
  FiZoomOut,
  FiRotateCcw,
  FiRotateCw,
  FiMove,
  FiCrop,
  FiSliders,
  FiDroplet,
  FiSun,
  FiMoon,
  FiCloud,
  FiCloudRain,
  FiCloudSnow,
  FiWind,
  FiCompass,
  FiNavigation,
  FiTarget,
  FiAnchor,
  FiAward,
  FiBriefcase,
  FiPackage,
  FiShoppingCart,
  FiCreditCard,
  FiDollarSign,
  FiPercent,
  FiTrendingDown,
  FiBarChart,
  FiPieChart,
  FiLayers,
  FiMonitor,
  FiSmartphone,
  FiTablet,
  FiWatch,
  FiHeadphones,
  FiSpeaker,
  FiPrinter,
  FiServer,
  FiHardDrive,
  FiCpu,
  FiMemoryStick,
  FiTerminal,
  FiCode,
  FiGithub,
  FiGitlab,
  FiBitbucket,
  FiFigma,
  FiFramer,
  FiInstagram,
  FiTwitter,
  FiFacebook,
  FiLinkedin,
  FiYoutube,
  FiTwitch,
  FiSlack,
  FiDiscord,
  FiSkype,
  FiZap,
  FiBattery,
  FiBatteryCharging,
  FiPlug,
  FiPower,
  FiToggleLeft,
  FiToggleRight
} from 'lucide-react';

// Remix Icons - For specific dashboard and admin features
export {
  RiDashboardLine,
  RiCalendarLine,
  RiTeamLine,
  RiFileTextLine,
  RiSettings4Line,
  RiToolsLine,
  Plus,
  RiBellLine,
  RiArrowLeftLine,
  RiEdit2Line,
  RiDeleteBinLine,
  RiSearchLine,
  RiFilterLine,
  RiDownloadLine,
  RiUploadLine,
  Eye,
  RiEyeOffLine,
  RiCheckLine,
  RiCloseLine,
  RiRefreshLine,
  RiMoreLine,
  RiMenuLine,
  RiLogoutBoxLine,
  RiUserLine,
  RiGroupLine,
  RiMailLine,
  RiLockLine,
  RiShieldLine,
  RiSecurePaymentLine,
  RiKeyLine,
  RiFingerprint2Line,
  RiShieldCheckLine,
  RiAlarmWarningLine,
  RiErrorWarningLine,
  RiInformationLine,
  RiQuestionLine,
  RiBookmarkLine,
  RiHeartLine,
  RiStarLine,
  RiThumbUpLine,
  RiShareLine,
  RiFlagLine,
  RiPriceTagLine,
  RiGridLine,
  RiListCheck,
  RiPlayLine,
  RiPauseLine,
  RiStopLine,
  RiSkipBackLine,
  RiSkipForwardLine,
  RiVolumeMuteLine,
  RiVolumeUpLine,
  RiShuffleLine,
  RiRepeatLine,
  RiZoomInLine,
  RiZoomOutLine,
  RiFullscreenLine,
  RiFullscreenExitLine,
  RiScreenshot2Line,
  RiCameraLine,
  RiVideoLine,
  RiMicLine,
  RiMicOffLine,
  RiSpeakerLine,
  RiHeadphoneLine,
  RiPhoneLine,
  RiMessageLine,
  RiChatSmileLine,
  RiSendPlaneLine,
  RiAttachmentLine,
  RiFolderLine,
  RiFolderOpenLine,
  RiFileLine,
  RiFileTextLine as RiFileTextLineAlt,
  RiFileImageLine,
  RiFileVideoLine,
  RiFileMusicLine,
  RiFileZipLine,
  RiFilePdfLine,
  RiFileWordLine,
  RiFileExcelLine,
  RiFilePptLine,
  RiDragDropLine,
  RiDragMoveLine,
  RiCropLine,
  RiScissorsLine,
  RiPaletteLine,
  RiBrushLine,
  RiPencilLine,
  RiMarkPenLine,
  RiEraserLine,
  RiDropLine,
  RiContrastLine,
  RiBrightnessLine,
  RiSunLine,
  RiMoonLine,
  RiCloudyLine,
  RiRainyLine,
  RiSnowyLine,
  RiWindyLine,
  RiThunderstormsLine,
  RiCompassLine,
  RiNavigationLine,
  RiMapPinLine,
  RiRoadMapLine,
  RiGlobalLine,
  RiEarthLine,
  RiPlanetLine,
  RiRocketLine,
  RiSpaceShipLine,
  RiAnchorLine,
  RiShipLine,
  RiCarLine,
  RiBusLine,
  RiTruckLine,
  RiBikeLine,
  RiMotorbikeLine,
  RiWalkLine,
  RiRunLine,
  RiFlightTakeoffLine,
  RiFlightLandLine,
  RiTrainLine,
  RiSubwayLine,
  RiTaxiLine,
  RiUberLine,
  RiHotelLine,
  RiBuildingLine,
  RiHomeLine,
  RiHome2Line,
  RiHome3Line,
  RiHome4Line,
  RiHome5Line,
  RiStore2Line,
  RiShoppingBagLine,
  RiShoppingCartLine,
  RiShoppingCart2Line,
  RiWalletLine,
  RiCoinLine,
  RiMoneyDollarCircleLine,
  RiBankCardLine,
  RiSecurePaymentLine as RiSecurePaymentLineAlt,
  RiRefund2Line,
  RiReceiptLine,
  RiBillLine,
  RiCalculatorLine,
  RiPercentLine,
  RiStockLine,
  RiLineChartLine,
  RiBarChartLine,
  RiPieChartLine,
  RiDonutChartLine,
  RiFundsLine,
  RiTrendingUpLine,
  RiTrendingDownLine,
  RiEqualizerLine,
  RiPulseLine,
  RiHeartPulseLine,
  RiMentalHealthLine,
  RiMedicineBottleLine,
  RiCapsuleLine,
  RiSyringeLine,
  RiThermometerLine,
  RiStethoscopeLine,
  RiHealthBookLine,
  RiFirstAidKitLine,
  RiHospitalLine,
  RiNurseLine,
  RiSurgicalMaskLine,
  RiVirusLine,
  RiBugLine,
  RiShieldVirusLine,
  RiTestTubeLine,
  RiMicroscopeLine,
  RiFlaskLine,
  RiAtomLine,
  RiDnaLine,
  RiLeafLine,
  RiSeedlingLine,
  RiTreeLine,
  RiFlowerLine,
  RiCactusLine,
  RiPlantLine,
  RiRecycleLine,
  RiEcoLine,
  RiFireLine,
  RiWaterLine,
  RiSnowflakeLine,
  RiLightbulbLine,
  RiFlashlightLine,
  RiBatteryLine,
  RiBatteryChargeLine,
  RiBatteryLowLine,
  RiChargingPileLine,
  RiPlugLine,
  RiUnplugLine,
  RiWifiLine,
  RiWifiOffLine,
  RiSignalTowerLine,
  RiBluetoothLine,
  RiBluetoothConnectLine,
  RiUsbLine,
  RiHardDriveLine,
  RiSaveLine,
  RiDatabase2Line,
  RiServerLine,
  RiCloudLine,
  RiCloudOffLine,
  RiCloudUploadLine,
  RiCloudDownloadLine,
  RiDownloadCloudLine,
  RiUploadCloudLine,
  RiDownload2Line,
  RiUpload2Line,
  RiShareForwardLine,
  RiShareBoxLine,
  RiLink,
  RiLinkUnlink,
  RiLinkM,
  RiExternalLinkLine,
  RiAnchorLine as RiAnchorLineAlt,
  RiHashtag,
  RiAtLine,
  RiQuestionMark,
  RiDoubleQuotesL,
  RiDoubleQuotesR,
  RiSingleQuotesL,
  RiSingleQuotesR,
  RiCopyrightLine,
  RiCreativeCommonsLine,
  RiRegisteredLine,
  RiTrademarkLine,
  RiPatentLine,
  RiAwardLine,
  RiMedalLine,
  RiTrophyLine,
  RiCupLine,
  RiVipCrownLine,
  RiVipCrown2Line,
  RiVipDiamondLine,
  RiGemLine,
  RiDiamondLine,
  RiCrownLine,
  RiKingLine,
  RiQueenLine,
  RiSwordLine,
  RiShieldLine as RiShieldLineAlt,
  RiShieldKeyholeLine,
  RiShieldStarLine,
  RiShieldUserLine,
  RiGovernmentLine,
  RiPoliceCarLine,
  RiSpyLine,
  RiUserSearchLine,
  RiUserFollowLine,
  RiUserUnfollowLine,
  RiUserStarLine,
  RiUserHeartLine,
  RiUserSmileLine,
  RiUserVoiceLine,
  RiUserLocationLine,
  RiUserSettingsLine,
  RiUserSharedLine,
  RiUserReceived2Line,
  RiUserAddLine,
  RiUserReduceLine,
  RiContactsLine,
  RiContactsBook2Line,
  RiContactsBookLine,
  RiAccountCircleLine,
  RiAccountBoxLine,
  RiAccountPinCircleLine,
  RiAccountPinBoxLine,
  RiProfileLine,
  RiUserLine as RiUserLineAlt,
  RiGroup2Line,
  RiGroupLine as RiGroupLineAlt,
  RiTeamLine as RiTeamLineAlt,
  RiOrganizationChart,
  RiParentLine,
  RiChildrenLine,
  RiBabyLine,
  RiWomenLine,
  RiMenLine,
  RiCommunityLine,
  RiFamilyLine,
  RiFriendsLine,
  RiEmotionHappyLine,
  RiEmotionNormalLine,
  RiEmotionSadLine,
  RiEmotionUnhappyLine,
  RiEmotionLine,
  RiEmotionLaughLine,
  RiGhost2Line,
  RiSkullLine,
  RiAlienLine,
  RiRobotLine,
  RiBearSmileLine,
  RiCatLine,
  RiDogLine,
  RiRabbitLine,
  RiHamsterLine,
  RiTurtleLine,
  RiFishLine,
  RiBugLine as RiBugLineAlt,
  RiButterfly2Line,
  RiSpiderLine,
  RiAntLine,
  RiHoneyLine,
  RiTreeLine as RiTreeLineAlt,
  RiParkLine,
  RiMapLine,
  RiMap2Line,
  RiEartquakeLine,
  RiFloodLine,
  RiTornadoLine,
  RiTyphoonLine,
  RiHailLine,
  RiMistLine,
  RiFoggyLine,
  RiCelsiusLine,
  RiFahrenheitLine,
  RiTempHotLine,
  RiTempColdLine,
  RiDrizzleLine,
  RiHeavyShowersLine,
  RiShowersLine,
  RiThunderstormsLine as RiThunderstormsLineAlt,
  RiHailLine as RiHailLineAlt,
  RiSnowyLine as RiSnowyLineAlt,
  RiBlizzardLine,
  RiWindyLine as RiWindyLineAlt,
  RiCloudWindyLine,
  RiMoonClearLine,
  RiMoonCloudyLine,
  RiMoonFoggyLine,
  RiSunCloudyLine,
  RiSunFoggyLine,
  RiSunLine as RiSunLineAlt,
  RiMoonLine as RiMoonLineAlt,
  RiStarLine as RiStarLineAlt,
  RiStarFillLine,
  RiStarSmileLine,
  RiMoonClearLine as RiMoonClearLineAlt,
  RiSunCloudyLine as RiSunCloudyLineAlt,
  RiCloudyLine as RiCloudyLineAlt,
  RiRainyLine as RiRainyLineAlt,
  RiSnowyLine as RiSnowyLineAlt2,
  RiWindyLine as RiWindyLineAlt2,
  RiThunderstormsLine as RiThunderstormsLineAlt2
} from 'lucide-react';

// Icon type definitions for better TypeScript support
export type FeatherIconType = React.ComponentType<React.SVGProps<SVGSVGElement>>;
export type RemixIconType = React.ComponentType<React.SVGProps<SVGSVGElement>>;

// Icon categories for organized usage
export const AuthIcons = {
  User: User as FiUser,
  Mail: Mail as FiMail,
  Lock: Lock as FiLock,
  UserCheck: UserCheck as FiUserCheck,
  Shield: Shield as FiShield,
  Key: RiKeyLine,
  Fingerprint: RiFingerprint2Line
} as const;

export const NavigationIcons = {
  Home: Home as FiHome,
  Dashboard: RiDashboardLine,
  Settings: Settings as FiSettings,
  ArrowLeft: FiArrowLeft,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  Menu: FiMenu,
  More: FiMoreVertical
} as const;

export const ActionIcons = {
  Edit: Edit as FiEdit,
  Delete: Trash2 as FiTrash2,
  Add: Plus as FiPlus,
  Save: Save as FiSave,
  Download: Download as FiDownload,
  Upload: Upload as FiUpload,
  Refresh: RefreshCw as FiRefreshCw,
  Search: FiSearch,
  Filter: FiFilter,
  Copy: FiCopy,
  Share: FiShare2
} as const;

export const StatusIcons = {
  Check: Check as FiCheck,
  X: X as FiX,
  AlertCircle: AlertCircle as FiAlertCircle,
  AlertTriangle: AlertTriangle as FiAlertTriangle,
  Info: FiInfo,
  Bell: FiBell,
  Star: FiStar,
  Heart: FiHeart
} as const;

export const SystemIcons = {
  Database: Database as FiDatabase,
  Server: FiServer,
  Activity: Activity as FiActivity,
  Cpu: FiCpu,
  HardDrive: FiHardDrive,
  Terminal: FiTerminal,
  Code: FiCode,
  Monitor: FiMonitor
} as const;

export const FileIcons = {
  File: FiFile,
  FileText: FileText as FiFileText,
  Folder: FiFolder,
  Image: FiImage,
  Video: FiVideo,
  Music: FiMusic,
  Paperclip: FiPaperclip
} as const;

export const CommunicationIcons = {
  MessageCircle: FiMessageCircle,
  Send: FiSend,
  Phone: FiPhone,
  Mail: Mail as FiMail,
  Bell: FiBell,
  Users: Users as FiUsers
} as const;

// Helper function to get icon by name (useful for dynamic icon rendering)
export function getIconByName(iconName: string): FeatherIconType | RemixIconType | null {
  const iconMap: Record<string, FeatherIconType | RemixIconType> = {
    // Auth
    'user': User as FiUser,
    'mail': Mail as FiMail,
    'lock': Lock as FiLock,
    'shield': Shield as FiShield,
    
    // Navigation
    'home': Home as FiHome,
    'dashboard': RiDashboardLine,
    'settings': Settings as FiSettings,
    'menu': FiMenu,
    
    // Actions
    'edit': Edit as FiEdit,
    'delete': Trash2 as FiTrash2,
    'add': Plus as FiPlus,
    'save': Save as FiSave,
    'download': Download as FiDownload,
    'upload': Upload as FiUpload,
    'search': FiSearch,
    'filter': FiFilter,
    
    // Status
    'check': Check as FiCheck,
    'x': X as FiX,
    'alert': AlertCircle as FiAlertCircle,
    'warning': AlertTriangle as FiAlertTriangle,
    'info': FiInfo,
    'bell': FiBell,
    
    // System
    'database': Database as FiDatabase,
    'server': FiServer,
    'activity': Activity as FiActivity,
    'cpu': FiCpu,
    'terminal': FiTerminal,
    
    // Files
    'file': FiFile,
    'folder': FiFolder,
    'image': FiImage,
    'video': FiVideo
  };
  
  return iconMap[iconName.toLowerCase()] || null;
}