version: '3.9'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: agendaiq-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agendaiq_test
    ports:
      - "5432:5432"
    volumes:
      - agendaiq_pg_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  agendaiq_pg_test_data:
    driver: local

