-- Database Restore Script
-- Generated from backup: 2025-08-09T07-04-04-465Z

BEGIN;

-- Disable triggers to avoid foreign key issues
SET session_replication_role = replica;

-- Insert District
INSERT INTO "District" ("name", "address", "code", "created_at", "id") VALUES ('CJCP Somerset', 'Somerset, NJ', 'CJCPS', '2025-08-09T05:15:58.917Z', 2);

-- Insert School
INSERT INTO "School" ("name", "address", "code", "created_at", "district_id", "id") VALUES ('CJCP Somerset Campus', 'Somerset, NJ', 'CJCPS-SOM', '2025-08-09T05:15:58.922Z', 2, 2);

-- Insert Department
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (2, 'SYS', 'System Management', 'Administration', 2, '2025-08-09T05:15:58.924Z', 0, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (3, 'SUPPORT', 'Student Support', 'Student Services', 2, '2025-08-09T05:15:58.925Z', 2, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (4, 'PURCHASE', 'Purchasing', 'Finance', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (5, 'GRANTS', 'Grants & Funding', 'Finance', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (6, 'AP', 'Accounts Payable', 'Finance', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (7, 'DATA', 'Data Management', 'Administration', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (8, 'ELEM', 'Elementary Education', 'Academic', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (9, 'HR', 'Human Resources', 'Administration', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (10, 'HEALTH', 'Health Services', 'Student Services', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (11, 'IT', 'Information Technology', 'Administration', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (12, 'EXEC', 'Executive Leadership', 'Administration', 2, '2025-08-09T05:15:58.924Z', 1, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (13, 'ADMIN_SUPPORT', 'Administrative Support', 'Administration', 2, '2025-08-09T05:15:58.924Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (14, 'OPS', 'Operations', 'Administration', 2, '2025-08-09T05:15:58.924Z', 2, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (15, 'EXEC_SUPPORT', 'Executive Support', 'Administration', 2, '2025-08-09T05:15:58.924Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (16, 'US_STEM', 'Upper School STEM', 'Academic', 2, '2025-08-09T05:15:58.924Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (17, 'HUM', 'Humanities', 'Academic', 2, '2025-08-09T05:15:58.924Z', 2, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (18, 'ASSESS', 'Assessment & Accountability', 'Academic', 2, '2025-08-09T05:15:58.925Z', 2, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (19, 'SPED', 'Special Education', 'Student Services', 2, '2025-08-09T05:15:58.924Z', 2, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (20, 'BUS', 'Business & Finance', 'Administration', 2, '2025-08-09T05:15:58.924Z', 2, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (21, 'ELECTIVES', 'Electives & Arts', 'Academic', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (22, 'CURR', 'Curriculum Development', 'Academic', 2, '2025-08-09T05:15:58.925Z', 2, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (23, 'ELEM_COACH', 'Elementary Coaching', 'Academic', 2, '2025-08-09T05:15:58.924Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (24, 'US_HUM', 'Upper School Humanities', 'Academic', 2, '2025-08-09T05:15:58.925Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (25, 'ATTENDANCE', 'Attendance Services', 'Administration', 2, '2025-08-09T05:15:58.924Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (26, 'SEC', 'Security & Safety', 'Administration', 2, '2025-08-09T05:15:58.924Z', 3, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (27, 'STEM', 'STEM', 'Academic', 2, '2025-08-09T05:15:58.924Z', 2, NULL);
INSERT INTO "Department" ("id", "code", "name", "category", "school_id", "created_at", "level", "parent_id") VALUES (30, 'DO', 'District Office', NULL, 2, '2025-08-09T06:28:56.943Z', 0, NULL);

-- Insert Role
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (10, 'Business Specialist (Grants)', 3, NULL, 5, '2025-08-09T05:15:58.955Z', false, 3, NULL, '1503', false, false, '3rd Floor');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (12, 'Director of Accountability', 2, NULL, 18, '2025-08-09T05:15:58.955Z', true, 2, NULL, '1696', false, true, '130');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (3, 'Chief Education Officer', 1, NULL, 12, '2025-08-09T05:15:58.955Z', true, 1, NULL, '1001', false, true, '501');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (17, 'Accounts Payable Specialist', 3, NULL, 6, '2025-08-09T05:15:58.955Z', false, 3, NULL, '1502', false, false, '3rd Floor');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (16, 'Elementary Coach', 3, NULL, 23, '2025-08-09T05:15:58.955Z', true, 3, NULL, '1131', false, true, '131');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (15, 'Director of Student Support Services', 2, NULL, 3, '2025-08-09T05:15:58.955Z', true, 2, NULL, '1105', false, true, '105');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (5, 'US Supervisor - STEM', 3, NULL, 16, '2025-08-09T05:15:58.955Z', true, 3, NULL, '1126', false, true, '126');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (6, 'Director of Operations', 2, NULL, 14, '2025-08-09T05:15:58.955Z', true, 2, NULL, '1125', false, true, '125');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (13, 'US Supervisor - Electives', 3, NULL, 21, '2025-08-09T05:15:58.955Z', true, 3, NULL, NULL, false, true, NULL);
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (8, 'Director of Special Education', 2, NULL, 19, '2025-08-09T05:15:58.955Z', true, 2, NULL, '1695', false, true, '130');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (4, 'System Administrator', 0, NULL, 2, '2025-08-09T05:15:58.955Z', true, 0, NULL, '9999', false, true, 'Server Room');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (7, 'Business Administrator', 2, NULL, 20, '2025-08-09T05:15:58.955Z', true, 2, NULL, NULL, false, true, NULL);
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (9, 'Elementary Supervisor', 3, NULL, 8, '2025-08-09T05:15:58.955Z', true, 3, NULL, '1122', false, true, '122');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (11, 'Purchasing Specialist', 3, NULL, 4, '2025-08-09T05:15:58.955Z', false, 3, NULL, '1501', false, false, '3rd Floor');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (14, 'School Secretary', 3, NULL, 13, '2025-08-09T05:15:58.955Z', false, 3, NULL, '1100', false, false, 'Main Office');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (2, 'Supervisors - Curriculum/Professional Development', 2, NULL, 22, '2025-08-09T05:15:58.955Z', true, 2, NULL, '1127', false, true, '127');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (19, 'Assistant Director of Student Support Services', 2, NULL, 3, '2025-08-09T05:15:58.956Z', true, 2, NULL, '1201', false, true, '201');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (20, 'Registrar & Data Management Specialist', 3, NULL, 7, '2025-08-09T05:15:58.956Z', false, 3, NULL, '1506', false, false, '3rd Floor');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (18, 'Assistant Business Administrator', 2, NULL, 20, '2025-08-09T05:15:58.955Z', true, 2, NULL, '1509', false, true, '3rd Floor');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (21, 'HR Payroll & Benefits Specialist', 3, NULL, 9, '2025-08-09T05:15:58.956Z', false, 3, NULL, '1504', false, false, '3rd Floor');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (22, 'School Nurse', 3, NULL, 10, '2025-08-09T05:15:58.956Z', false, 3, NULL, '1694', false, false, '630');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (23, 'HR Specialist', 3, NULL, 9, '2025-08-09T05:15:58.956Z', false, 3, NULL, '1507', false, false, '3rd Floor');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (24, 'IT Manager', 3, NULL, 11, '2025-08-09T05:15:58.956Z', true, 3, NULL, '1650', false, true, '600 hw');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (25, 'Head of Security', 3, NULL, 26, '2025-08-09T05:15:58.956Z', true, 3, NULL, '1101', false, true, '101');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (26, 'US Supervisor - Humanities', 3, NULL, 24, '2025-08-09T05:15:58.956Z', true, 3, NULL, NULL, false, true, NULL);
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (27, 'Social Worker', 4, NULL, 3, '2025-08-09T05:15:58.956Z', false, 4, NULL, '1104', false, false, '104');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (28, 'School Counselor', 4, NULL, 3, '2025-08-09T05:15:58.956Z', false, 4, NULL, '1103', false, false, '104');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (29, 'IT Specialist', 3, NULL, 11, '2025-08-09T05:15:58.956Z', false, 3, NULL, '1652', false, false, '200 hw');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (30, 'Academic Counselor', 4, NULL, 3, '2025-08-09T05:15:58.956Z', false, 4, NULL, '1697', false, false, '634');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (31, 'School Psychologist', 4, NULL, 3, '2025-08-09T05:15:58.956Z', false, 4, NULL, '1704', false, false, '123');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (33, 'Chronic Absenteeism Specialist', 3, NULL, 25, '2025-08-09T05:15:58.956Z', false, 3, NULL, '1702', false, false, 'Main Office');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (34, 'Behavioral Specialist', 4, NULL, 3, '2025-08-09T05:15:58.956Z', false, 4, NULL, '1701', false, false, 'TBD');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (35, 'Teacher', 4, NULL, 17, '2025-08-09T05:15:58.956Z', false, 4, NULL, NULL, false, false, NULL);
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (32, 'Director of Curriculum - STEM', 2, NULL, 27, '2025-08-09T05:15:58.956Z', true, 2, NULL, '1126', false, true, '126');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (36, 'Executive Administrative Assistant', 3, NULL, 15, '2025-08-09T05:15:58.956Z', false, 3, NULL, '1508', false, false, '3rd Floor');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (37, 'Director of Curriculum - Humanities', 2, NULL, 17, '2025-08-09T05:15:58.956Z', true, 2, NULL, '1124', false, true, '124');
INSERT INTO "Role" ("id", "title", "priority", "category", "department_id", "created_at", "is_leadership", "level", "parent_id", "extension", "is_coordinator", "is_supervisor", "room") VALUES (38, 'Administrator', 0, 'executive', NULL, '2025-08-09T05:23:36.406Z', true, 0, NULL, NULL, false, false, NULL);

-- Insert users
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (6, 'sysadmin@cjcollegeprep.org', 'System Administrator', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, true, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.219Z', '2025-08-09T05:15:59.219Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (7, 'fbrown@cjcollegeprep.org', 'Ms. Brown', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (8, 'namin@cjcollegeprep.org', 'Ms. Nima Amin', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.219Z', '2025-08-09T05:15:59.219Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (9, 'amygettelfinger@cjcollegeprep.org', 'Ms. Gettelfinger', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (10, 'tsalley@cjcollegeprep.org', 'Ms. Salley', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (11, 'cthomas@cjcollegeprep.org', 'Ms. Thomas', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (13, 'purchasing@cjcollegeprep.org', 'Ms. Ramos', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (12, 'lmignogno@cjcollegeprep.org', 'Ms. Mignogno', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (14, 'mfirsichbaum@cjcollegeprep.org', 'Ms. Firsichbaum', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (15, 'cmathews@cjcollegeprep.org', 'Dr. Mathews', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (16, 'braybon@cjcollegeprep.org', 'Ms. Raybon', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (17, 'manar@cjcollegeprep.org', 'Mr. Anar', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (18, 'hr@cjcollegeprep.org', 'Ms. Goldstein', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (19, 'bgrossmann@cjcollegeprep.org', 'Ms. Grossmann', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (20, 'nsercan@cjcollegeprep.org', 'Dr. Namik Sercan', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, true, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.219Z', '2025-08-09T05:15:59.219Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (21, 'dcua@cjcollegeprep.org', 'Mr. Daryl', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (22, 'skaeli@cjcollegeprep.org', 'Ms. Kaeli', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (23, 'jantonacci@cjcollegeprep.org', 'Ms. Antonacci', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (26, 'bagudelo@cjcollegeprep.org', 'Ms. Bibiana', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (27, 'abicer@cjcollegeprep.org', 'Mr. Ahmet', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (25, 'pespinoza@cjcollegeprep.org', 'Ms. Espinoza', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (28, 'vsuslu@cjcollegeprep.org', 'Mr. Bright', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (29, 'fbarker@cjcollegeprep.org', 'Ms. Brown', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (30, 'mgibbs@cjcollegeprep.org', 'Ms. Gibbs', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (31, 'kmercedes@cjcollegeprep.org', 'Ms. Mercedes', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (24, 'accountspayable@cjcollegeprep.org', 'Ms. Mancuso', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (33, 'skeskin@cjcollegeprep.org', 'Ms. Keskin', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (34, 'cpagliuca@cjcollegeprep.org', 'Ms. Pagliuca', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (35, 'stayfur@cjcollegeprep.org', 'Mr. Tayfur', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (36, 'scerone@cjcollegeprep.org', 'Ms. Cerone', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (32, 'myilmaz@cjcollegeprep.org', 'Mr. Mert', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (38, 'sba@cjcollegeprep.org', 'Ms. Daubon', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (39, 'ahauser@cjcollegeprep.org', 'Ms. Hauser', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (40, 'smeyer@cjcollegeprep.org', 'Ms. Meyer', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (41, 'imlladenovic@cjcollegeprep.org', 'Ms. Mladenovic', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (42, 'kbarkohani@cjcollegeprep.org', 'Ms. Barkohani', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (43, 'asimon@cjcollegeprep.org', 'Ms. Simon', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (44, 'ninanir@cjcollegeprep.org', 'Ms. Neval', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (45, 'djacobs@cjcollegeprep.org', 'Ms. Jacobs', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (46, 'jtadros@cjcollegeprep.org', 'Ms. Tadros', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (48, 'palvarez@cjcollegeprep.org', 'Ms. Alvarez', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (49, 'dvesper@cjcollegeprep.org', 'Dr. Vesper', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (37, 'ktemplasky@cjcollegeprep.org', 'Mr. Tempalsky', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (50, 'ekeating@cjcollegeprep.org', 'Ms. Keating', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (51, 'hrdept@cjcollegeprep.org', 'Ms. LaLindez', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (53, 'cquerijero@cjcollegeprep.org', 'Ms. Querijero', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (52, 'ldobrin@cjcollegeprep.org', 'Ms. Dobrin', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (54, 'mmontgomery@cjcollegeprep.org', 'Ms. Montgomery', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (55, 'akahraman@cjcollegeprep.org', 'Mr. Kahraman', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (56, 'admin@school.edu', 'Admin User', NULL, '$2b$10$kBUvH7JxDYQixYgEiZJMAuAjuRfDlMGxwkbpKWyABvu/E80e1w6jq', NULL, NULL, true, false, NULL, '{}', true, true, true, '2025-08-09T05:17:04.859Z', '2025-08-09T06:44:09.754Z', 'tasarim', 'compact');
INSERT INTO "users" ("id", "email", "name", "staff_id", "hashedPassword", "emailVerified", "image", "is_admin", "two_factor_enabled", "two_factor_secret", "backup_codes", "login_notifications_enabled", "suspicious_alerts_enabled", "remember_devices_enabled", "created_at", "updated_at", "theme_preference", "layout_preference") VALUES (47, 'rorhan@cjcollegeprep.org', 'Ms. Orhan', NULL, '$2b$12$gjKyWbUmBt7gqVj9kjPQIOPl28U2SMqkD/1nOiysk4UMUcZ0U5DGO', NULL, NULL, false, false, NULL, '{}', true, true, true, '2025-08-09T05:15:59.220Z', '2025-08-09T05:15:59.220Z', 'standard', 'modern');

-- Insert Staff
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (4, 20, 12, 3, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1001', NULL, true, '501');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (5, 38, 20, 18, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1509', NULL, true, '3rd Floor');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (6, 28, 3, 15, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1105', NULL, true, '105');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (7, 17, 20, 7, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', NULL, NULL, true, NULL);
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (8, 6, 2, 4, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '9999', NULL, true, 'Server Room');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (9, 12, 22, 2, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1127', NULL, true, '127');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (10, 8, 14, 6, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1125', NULL, true, '125');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (11, 16, 25, 33, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1702', NULL, true, 'Main Office');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (12, 31, 15, 36, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1508', NULL, true, '3rd Floor');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (13, 29, 16, 5, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1126', NULL, true, '126');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (14, 19, 3, 19, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1201', NULL, true, '201');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (16, 40, 5, 10, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1503', NULL, true, '3rd Floor');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (17, 18, 9, 21, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1504', NULL, true, '3rd Floor');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (18, 11, 17, 37, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1124', NULL, true, '124');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (19, 23, 10, 22, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1694', NULL, true, '630');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (20, 14, 8, 9, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.245Z', '1122', NULL, true, '122');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (21, 9, 23, 16, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1131', NULL, true, '131');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (22, 30, 21, 13, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', NULL, NULL, true, NULL);
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (23, 21, 11, 29, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1652', NULL, true, '200 hw');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (24, 26, 11, 29, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1652', NULL, true, '200 hw');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (25, 37, 26, 25, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1101', NULL, true, '101');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (15, 51, 9, 23, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1507', NULL, true, '3rd Floor');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (26, 49, 19, 8, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1695', NULL, true, '130');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (27, 15, 24, 26, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', NULL, NULL, true, NULL);
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (28, 10, 13, 14, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1100', NULL, true, 'Main Office');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (29, 27, 11, 29, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1652', NULL, true, '200 hw');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (30, 33, 3, 30, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1697', NULL, true, '634');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (31, 25, 13, 14, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1100', NULL, true, 'Main Office');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (32, 44, 3, 30, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1697', NULL, true, '634');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (33, 39, 3, 28, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1103', NULL, true, '104');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (34, 36, 3, 28, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1103', NULL, true, '104');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (35, 32, 11, 29, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1652', NULL, true, '200 hw');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (36, 48, 3, 28, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1103', NULL, true, '104');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (37, 52, 3, 28, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1103', NULL, true, '104');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (38, 42, 3, 28, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1103', NULL, true, '104');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (39, 41, 3, 28, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1103', NULL, true, '104');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (40, 46, 3, 27, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1104', NULL, true, '104');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (41, 47, 3, 27, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1104', NULL, true, '104');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (42, 43, 3, 27, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1104', NULL, true, '104');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (43, 45, 3, 34, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1701', NULL, true, 'TBD');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (44, 50, 3, 31, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1704', NULL, true, '123');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (45, 24, 6, 17, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1502', NULL, true, '3rd Floor');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (46, 53, 10, 22, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1694', NULL, true, '630');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (47, 35, 11, 24, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1650', NULL, true, '600 hw');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (48, 13, 4, 11, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1501', NULL, true, '3rd Floor');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (49, 7, 27, 32, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1126', NULL, true, '126');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (50, 34, 7, 20, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1506', NULL, true, '3rd Floor');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (51, 22, 18, 12, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1696', NULL, true, '130');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (52, 54, 10, 22, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1694', NULL, true, '630');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (53, 55, 11, 24, NULL, '{active}', '{}', 2, 2, '2025-08-09T05:15:59.246Z', '1650', NULL, true, '600 hw');
INSERT INTO "Staff" ("id", "user_id", "department_id", "role_id", "manager_id", "flags", "endorsements", "school_id", "district_id", "created_at", "extension", "hire_date", "is_active", "room") VALUES (54, 56, 30, 38, NULL, '{active,admin,leadership}', '{}', 2, 2, '2025-08-09T05:24:52.556Z', '1000', '2020-01-01T00:00:00.000Z', true, '500');

-- Insert Meeting
INSERT INTO "Meeting" ("title", "description", "created_at", "department_id", "district_id", "end_time", "organizer_id", "school_id", "start_time", "zoom_join_url", "zoom_meeting_id", "id", "action_items", "agenda", "calendar_integration", "decisions", "is_continuation", "meeting_type", "notes", "parent_meeting_id", "repeat_type", "status", "template_id", "is_series_master", "repeat_end_date", "repeat_end_type", "repeat_exceptions", "repeat_interval", "repeat_month_day", "repeat_month_week", "repeat_month_weekday", "repeat_occurrences", "repeat_pattern", "repeat_weekdays", "series_id", "series_position") VALUES ('Deneme', 'Deneme meeting''i', '2025-08-09T06:14:50.262Z', 12, 2, '2025-08-09T13:30:00.000Z', 54, 2, '2025-08-09T13:00:00.000Z', NULL, NULL, 1, NULL, NULL, NULL, NULL, false, 'regular', NULL, NULL, NULL, 'scheduled', NULL, true, NULL, NULL, '{}', NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 1);

-- Insert MeetingAttendee
INSERT INTO "MeetingAttendee" ("status", "created_at", "meeting_id", "staff_id", "id") VALUES ('pending', '2025-08-09T06:14:50.262Z', 1, 27, 1);
INSERT INTO "MeetingAttendee" ("status", "created_at", "meeting_id", "staff_id", "id") VALUES ('pending', '2025-08-09T06:14:50.262Z', 1, 4, 2);
INSERT INTO "MeetingAttendee" ("status", "created_at", "meeting_id", "staff_id", "id") VALUES ('pending', '2025-08-09T06:14:50.262Z', 1, 26, 3);
INSERT INTO "MeetingAttendee" ("status", "created_at", "meeting_id", "staff_id", "id") VALUES ('pending', '2025-08-09T06:14:50.262Z', 1, 29, 4);
INSERT INTO "MeetingAttendee" ("status", "created_at", "meeting_id", "staff_id", "id") VALUES ('pending', '2025-08-09T06:14:50.262Z', 1, 7, 5);

-- Insert meeting_agenda_items
INSERT INTO "meeting_agenda_items" ("id", "meeting_id", "topic", "problem_statement", "staff_initials", "responsible_staff_id", "priority", "purpose", "proposed_solution", "solution_type", "decisions_actions", "decision_type", "status", "future_implications", "order_index", "duration_minutes", "created_at", "updated_at", "carried_forward", "carry_forward_count", "parent_item_id", "responsible_role_id") VALUES (1, 1, 'Ilk madde', 'Bu madde searchh icin kullanılacak. Bakalım calisacak mi?', NULL, 54, 'Medium', 'Discussion', NULL, NULL, NULL, NULL, 'Pending', false, 0, 15, '2025-08-09T06:17:16.308Z', '2025-08-09T06:17:16.308Z', false, 0, NULL, NULL);

-- Insert audit_logs
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (1, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to classic-light', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:18.000Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (2, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to classic-dark', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:22.225Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (3, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to midnight-blue', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:25.698Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (4, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to forest-green', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:30.870Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (5, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to warm-orange', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:33.441Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (6, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to tasarim', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:36.354Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (7, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to modern-purple', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:39.577Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (8, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to dark-mode', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:42.366Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (9, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to high-contrast', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:45.138Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (10, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to nature-green', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:54:48.614Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (11, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to standard', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:55:05.415Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (12, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, NULL, 'WEB_UI', 'Theme changed to tasarim', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T05:55:07.972Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (13, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, 54, 'WEB_UI', 'Layout changed to classic', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T06:43:51.713Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (14, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, 54, 'WEB_UI', 'Layout changed to modern', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T06:44:03.146Z');
INSERT INTO "audit_logs" ("id", "table_name", "record_id", "operation", "field_changes", "old_values", "new_values", "user_id", "staff_id", "source", "description", "ip_address", "user_agent", "metadata", "created_at") VALUES (15, 'users', '56', 'UPDATE', NULL, NULL, NULL, 56, 54, 'WEB_UI', 'Layout changed to compact', '::1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15', NULL, '2025-08-09T06:44:09.762Z');


-- Update sequences
SELECT setval('users_id_seq', (SELECT COALESCE(MAX(id), 1) FROM users));
SELECT setval('"District_id_seq"', (SELECT COALESCE(MAX(id), 1) FROM "District"));
SELECT setval('"School_id_seq"', (SELECT COALESCE(MAX(id), 1) FROM "School"));
SELECT setval('"Department_id_seq"', (SELECT COALESCE(MAX(id), 1) FROM "Department"));
SELECT setval('"Role_id_seq"', (SELECT COALESCE(MAX(id), 1) FROM "Role"));
SELECT setval('"Staff_id_seq"', (SELECT COALESCE(MAX(id), 1) FROM "Staff"));
SELECT setval('"Meeting_id_seq"', (SELECT COALESCE(MAX(id), 1) FROM "Meeting"));
SELECT setval('"MeetingAttendee_id_seq"', (SELECT COALESCE(MAX(id), 1) FROM "MeetingAttendee"));

-- Re-enable triggers
SET session_replication_role = DEFAULT;

COMMIT;
