#!/bin/bash

# Validation Agent Global Installer
# This script makes the validation agent available system-wide

AGENT_PATH="$(pwd)/.claude/validation-agent.js"
AGENT_NAME="agendaiq-validator"

echo "Installing AgendaIQ Validation Agent globally..."

# Create a wrapper script
cat > /tmp/${AGENT_NAME} << EOF
#!/bin/bash
# AgendaIQ Validation Agent Wrapper
# Auto-generated by install-validation-agent.sh

PROJECT_DIR="${PWD}"

# Check if we're in a project directory
if [ ! -f "\${PROJECT_DIR}/.claude/validation-agent.js" ]; then
    echo "Error: validation-agent.js not found in \${PROJECT_DIR}/.claude/"
    echo "Make sure you're in the AgendaIQ project directory"
    exit 1
fi

# Run the validation agent
cd "\${PROJECT_DIR}"
node "\${PROJECT_DIR}/.claude/validation-agent.js" "\$@"
EOF

# Make it executable
chmod +x /tmp/${AGENT_NAME}

# Move to user's local bin (create if doesn't exist)
mkdir -p ~/bin
mv /tmp/${AGENT_NAME} ~/bin/

# Add ~/bin to PATH if not already there
if [[ ":$PATH:" != *":$HOME/bin:"* ]]; then
    echo 'export PATH="$HOME/bin:$PATH"' >> ~/.zshrc
    echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
    echo "Added ~/bin to PATH in shell config files"
fi

echo "✅ Installation complete!"
echo ""
echo "Usage:"
echo "  1. Open any terminal"
echo "  2. Navigate to AgendaIQ project: cd $(pwd)"
echo "  3. Run: ${AGENT_NAME}"
echo ""
echo "To run in background:"
echo "  ${AGENT_NAME} &"
echo ""
echo "To stop the agent:"
echo "  pkill -f validation-agent.js"
echo ""
echo "Note: You may need to restart your terminal or run 'source ~/.zshrc' for PATH changes to take effect"